from django.urls import path
from .views import (
    home,
    champions_view,
    commissioner_keepers_view,
    constitution_view,
    draft_add_comment_view,
    draft_add_media_view,
    draft_update_view,
    drafts_view,
    hall_view,
    hottest_coldest_view,
    keeper_deadline_update_view,
    rules_view,
    settings_view,
    submit_rule_view,
    vote_rule_view,
    standings_view,
    keeper_history_view,
    submit_keepers_view,
    team_detail_view,
)

urlpatterns = [
    path("", home, name="home"),
    path("champions/", champions_view, name="champions"),
    path("constitution/", constitution_view, name="constitution"),
    path("drafts/", drafts_view, name="drafts"),
    path("drafts/<int:season_id>/update/", draft_update_view, name="draft_update"),
    path("drafts/<int:draft_id>/comment/", draft_add_comment_view, name="draft_add_comment"),
    path("drafts/<int:draft_id>/media/", draft_add_media_view, name="draft_add_media"),
    path("hall/", hall_view, name="hall"),
    path("hottest-coldest/", hottest_coldest_view, name="hottest_coldest"),
    path("keepers/deadline/", keeper_deadline_update_view, name="keeper_deadline_update"),
    path("rules/", rules_view, name="rules"),
    path("rules/submit/", submit_rule_view, name="submit_rule"),
    path("rules/<int:proposal_id>/vote/", vote_rule_view, name="vote_rule"),
    path("standings/", standings_view, name="standings"),
    path("settings/", settings_view, name="settings"),
    path("keepers/history/", keeper_history_view, name="keeper_history"),
    path("keepers/review/", commissioner_keepers_view, name="commissioner_keepers"),
    path("keepers/submit/", submit_keepers_view, name="submit_keepers"),
    path("team/<int:team_id>/", team_detail_view, name="team_detail"),
]