# Generated by Django 4.2.29 on 2026-03-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaguehub", "0003_alter_managerprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
