# Generated by Django 4.2.29 on 2026-03-23 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leaguehub", "0004_add_season_logo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.PositiveIntegerField()),
                ("pick", models.PositiveIntegerField()),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_picks",
                        to="leaguehub.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_picks",
                        to="leaguehub.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_picks",
                        to="leaguehub.team",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "pick"],
                "unique_together": {("season", "round", "pick")},
            },
        ),
    ]
