# Generated by Django 4.2.29 on 2026-05-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaguehub", "0008_player_weekly_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="managerprofile",
            name="is_commissioner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="is_officer",
            field=models.BooleanField(default=False),
        ),
    ]
