# Generated by Django 4.2.29 on 2026-05-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leaguehub", "0011_mediacomment_mediareaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("add", "Add"), ("drop", "Drop"), ("trade", "Trade")],
                        max_length=10,
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=150)),
                ("player_name", models.CharField(blank=True, max_length=150)),
                ("detail", models.CharField(blank=True, max_length=400)),
                ("occurred_at", models.DateTimeField()),
                (
                    "yahoo_transaction_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="leaguehub.season",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
    ]
