# Generated by Django 4.2.29 on 2026-05-07 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leaguehub", "0012_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="SleeperLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("league_id", models.CharField(max_length=64, unique=True)),
                ("season_year", models.PositiveIntegerField(db_index=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(blank=True, max_length=30)),
                ("previous_league_id", models.CharField(blank=True, max_length=64)),
                ("total_rosters", models.PositiveIntegerField(default=10)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-season_year"],
            },
        ),
        migrations.CreateModel(
            name="SleeperPlayer",
            fields=[
                (
                    "sleeper_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("first_name", models.CharField(blank=True, max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("position", models.CharField(blank=True, max_length=10)),
                ("nfl_team", models.CharField(blank=True, max_length=10)),
                ("status", models.CharField(blank=True, max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="managerprofile",
            name="sleeper_user_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name="SleeperTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sleeper_txn_id", models.CharField(max_length=64, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("free_agent", "Free Agent"),
                            ("waiver", "Waiver"),
                            ("trade", "Trade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=20)),
                ("week", models.PositiveIntegerField(blank=True, null=True)),
                ("adds", models.JSONField(default=dict)),
                ("drops", models.JSONField(default=dict)),
                ("roster_ids", models.JSONField(default=list)),
                ("waiver_bid", models.PositiveIntegerField(blank=True, null=True)),
                ("draft_picks", models.JSONField(default=list)),
                ("created_at", models.DateTimeField()),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sleeper_transactions",
                        to="leaguehub.sleeperleague",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SleeperRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roster_id", models.PositiveIntegerField()),
                ("owner_id", models.CharField(blank=True, max_length=64)),
                ("team_name", models.CharField(blank=True, max_length=150)),
                ("avatar_id", models.CharField(blank=True, max_length=100)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("ties", models.PositiveIntegerField(default=0)),
                (
                    "points_for",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "points_against",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("players", models.JSONField(default=list)),
                ("taxi_players", models.JSONField(default=list)),
                ("reserve_players", models.JSONField(default=list)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rosters",
                        to="leaguehub.sleeperleague",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sleeper_rosters",
                        to="leaguehub.managerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "roster_id"],
                "unique_together": {("league", "roster_id")},
            },
        ),
        migrations.CreateModel(
            name="SleeperChampion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "league",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="champion",
                        to="leaguehub.sleeperleague",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="championships",
                        to="leaguehub.sleeperroster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SleeperTradedPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_year", models.PositiveIntegerField()),
                ("round", models.PositiveIntegerField()),
                ("roster_id", models.PositiveIntegerField()),
                ("previous_owner_id", models.PositiveIntegerField()),
                ("owner_id", models.PositiveIntegerField()),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traded_picks",
                        to="leaguehub.sleeperleague",
                    ),
                ),
            ],
            options={
                "ordering": ["season_year", "round", "roster_id"],
                "unique_together": {
                    ("league", "season_year", "round", "roster_id", "owner_id")
                },
            },
        ),
        migrations.CreateModel(
            name="SleeperMatchup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.PositiveIntegerField()),
                ("matchup_id", models.PositiveIntegerField()),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_playoff", models.BooleanField(default=False)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchups",
                        to="leaguehub.sleeperleague",
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchups",
                        to="leaguehub.sleeperroster",
                    ),
                ),
            ],
            options={
                "ordering": ["league__season_year", "week", "matchup_id"],
                "unique_together": {("league", "week", "roster")},
            },
        ),
        migrations.CreateModel(
            name="SleeperDraftPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("draft_id", models.CharField(blank=True, max_length=64)),
                ("round", models.PositiveIntegerField()),
                ("pick_no", models.PositiveIntegerField()),
                ("roster_id", models.PositiveIntegerField()),
                ("player_name", models.CharField(blank=True, max_length=150)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_results",
                        to="leaguehub.sleeperleague",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_picks",
                        to="leaguehub.sleeperplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["round", "pick_no"],
                "unique_together": {("league", "draft_id", "round", "pick_no")},
            },
        ),
    ]
