# Generated by Django 4.2.29 on 2026-05-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaguehub", "0013_sleeper_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sleeperplayer",
            name="status",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
